experiment_name: smd_deberta_base_closure
destpath: ./runs/smd_deberta_base_closure/
datapath: ../data/SMD/
dataset_name: SMD
hint: closure

model:
  max_input_length: 1024
  wildcard: 'microsoft/deberta-v3-base'
  use_kb: False
  ctx_length: 1

train:
  per_device_train_batch_size: 16
  gradient_accumulation_steps: 1
  gradient_checkpointing: false
  learning_rate: 0.00003
  num_epochs: 5
  seed: 42
  fp16: False
  save_eval_steps: 100
  resume_training: True
  save_total_limit: 2
  metric_for_best_model: accuracy
  greater_is_better: True
  early_stopping_patience: 5
  warmup_ratio: 0.1

dev:
  per_device_eval_batch_size: 4
  sample: False
  num_beams: 1
  max_resp_length: 128
  top_k: 8
  top_p: 0.9
  temperature: 0.85

use_wandb: True
